server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.26.2.9:8761/eureka

spring:
  application:
    name: maryfarm-apigateway-service
  rabbitmq:
    host: 172.26.2.9
    port: 5672
    username: guest
    password: guest
  # zipkin:
  #   base-url: http://127.0.0.1:9411
  #   enabled: true
  # sleuth:
  #   sampler:
  #   probability: 1.0
  cloud:
    gateway:
      routes:
        - id: maryfarm-user-service
          uri: lb://MARYFARM-USER-SERVICE
          predicates:
            - Path=/maryfarm-user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/maryfarm-user-service/(?<segment>.*), /$\{segment}
        - id: maryfarm-notify-service
          uri: lb://MARYFARM-NOTIFY-SERVICE
          predicates:
            - Path=/maryfarm-notify-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/maryfarm-notify-service/(?<segment>.*), /$\{segment}
        - id: maryfarm-chat-service
          uri: lb://MARYFARM-CHAT-SERVICE
          predicates:
            - Path=/maryfarm-chat-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/maryfarm-chat-service/(?<segment>.*), /$\{segment}
        - id: maryfarm-plant-service
          uri: lb://MARYFARM-PLANT-SERVICE
          predicates:
            - Path=/maryfarm-plant-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/maryfarm-plant-service/(?<segment>.*), /$\{segment}
        - id: maryfarm-calendar-service
          uri: lb://MARYFARM-CALENDAR-SERVICE
          predicates:
            - Path=/maryfarm-calendar-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/maryfarm-calendar-service/(?<segment>.*), /$\{segment}
        - id: maryfarm-board-service
          uri: lb://MARYFARM-BOARD-SERVICE
          predicates:
            - Path=/maryfarm-board-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/maryfarm-board-service/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus
